name: holoviews
channels:
  - conda-forge
dependencies:
  - bokeh
  - datashader
  - jupyter_bokeh
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - panel
  - pip=21.1.3
  - python=3.9.6
  - pyviz_comms
